### ISSUE TITLE
Migrate code to Scala

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/NGSI-LD_Wrapper.old#13]
We are not happy with Jersey nor with the Java approach. 

Plan is to migrate code to Scala + Scalatra. Simple framework.

**Comment by jmcanterafonseca** [comment]
Code has been migrated. New repo NGSI-LD_Wrapper has been created. This repo will be deleted in two days. 

Dear watchers and stargazers, please could you move to the new repository

@fisuda @fgalan @nikoskal @juliozinga @namingFail @pietercolpaert

**Comment by pietercolpaert** [comment]
Link to that one for the sake of links ;-) https://github.com/Fiware/NGSI-LD_Wrapper
